//gET TYPE OF POKEMONS
export const GETING_TYPES = "GETING_TYPES";
export const FETCH_TYPES_SUCCESS = "FETCH_TYPES_SUCCESS";
export const FETCH_TYPES_ERROR = "FETCH_TYPES_ERROR";
//GET ABILITIES OF POKEMONS
export const GETING_ABILITIES = "GETING_ABILITIES";
export const FETCH_ABILITIES_SUCCESS = "FETCH_ABILITIES_SUCCESS";
export const FETCH_ABILITIES_ERROR = "FETCH_ABILITIES_ERROR";
//GET POKEMONS BY NAME
export const GETING_POKEMONS = "GETING_POKEMONS";
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_ERROR = "FETCH_POKEMONS_ERROR";
